# docker-compose.yml

version: '3.8'
services:

  db:
    container_name: 'db'
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    container_name: 'app'
    restart: on-failure
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - /Users/begaiyma/Desktop/Work/M/nodejs/nodejs2023Q2-service/src:/app/src

volumes:
  postgres:

networks:
  app-network:
    driver: bridge