# docker-compose.yml

version: '3.8'
services:

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    restart: always
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db

volumes:
  postgres: